<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:ns0="http://xmlns.oracle.com/TestSOAApplication/TestProject/BPELProcess3"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://xmlns.oracle.com/xdb/TEST"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://oracle.com/sca/soapservice/TestSOAApplication/EDNPerformanceProject/SOAPService">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/BPELProcess3.wsdl"/>
                <oracle-xsl-mapper:rootElement name="process"
                                               namespace="http://xmlns.oracle.com/TestSOAApplication/TestProject/BPELProcess3"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="http://localhost:7001/soa-infra/services/default/EDNPerformanceProject!1.0/WSDLs/SOAPService.wsdl"/>
                <oracle-xsl-mapper:rootElement name="MESSAGE_TYP" namespace="http://xmlns.oracle.com/xdb/TEST"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON SEP 12 15:40:57 CEST 2016].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:MESSAGE_TYP>
            <SUBJECT>
                <xsl:value-of select="/ns0:process/ns0:input"/>
            </SUBJECT>
            <TEXT>
                <xsl:value-of select="/ns0:process/ns0:input"/>
            </TEXT>
        </tns:MESSAGE_TYP>
    </xsl:template>
</xsl:stylesheet>
