<wsdl:definitions
     name="aqReference"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/aq/TestSOAApplication/TestEnqueueProj/aqReference"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/aq/TestSOAApplication/TestEnqueueProj/aqReference"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:obj1="http://xmlns.oracle.com/xdb/TEST"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="Enqueue_plt" >
    <plt:role name="Enqueue_role" >
      <plt:portType name="tns:Enqueue_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/xdb/TEST" schemaLocation="../Schemas/TEST_MESSAGE_TYP.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="MESSAGE_TYP_msg">
        <wsdl:part name="MESSAGE_TYP" element="obj1:MESSAGE_TYP"/>
    </wsdl:message>
    <wsdl:portType name="Enqueue_ptt">
        <wsdl:operation name="Enqueue">
            <wsdl:input message="tns:MESSAGE_TYP_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
