<wsdl:definitions
     name="testdbService"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TestSOAApplication/TestEnqueueProj/testdbService"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TestSOAApplication/TestEnqueueProj/testdbService"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/testdbService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="testdbService_plt" >
    <plt:role name="testdbService_role" >
      <plt:portType name="tns:testdbService_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/testdbService" schemaLocation="../Schemas/testdbService_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="TestenqueueCollection_msg">
        <wsdl:part name="TestenqueueCollection" element="top:TestenqueueCollection"/>
    </wsdl:message>
    <wsdl:portType name="testdbService_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:TestenqueueCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
